name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build and Release"
    runs-on: ubuntu-latest
    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
        - 8000:8000
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install requirements.txt
        run: |
          pip3 install -r ./requirements.txt
          pip3 install pytest pytest-cov
      - name: Run tests
        run: |
          pytest
          pytest --cov .
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install serverless
        run: npm install -g serverless serverless-python-requirements
